# Generated by Django 3.2.5 on 2022-04-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
